baseURL: "https://ramanebrahimi.github.io/" 
title: Raman Ebrahimi
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        # - name: Books
        #   url: books/
        #   weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Projects
          url: data/
          weight: 4 
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    description: "I am a Professor of Philology at the Institute of Romance Philology in Regensburg, Germany. My research focuses mostly on Portuguese irregular verbs."
    author: Moritz-Maria von Igelfeld
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Raman Ebrahimi
          subtitle: "Hello! This is Raman. I'm a Ph.D. student in Machine Learning and Data Science at the University of California San Diego, advised by [Dr. Parinaz Naghizadeh](https://parinazn.com/group/). My research focuses on the intersection of Network Science, Game Theory, and Optimization, specifically investigating socio-technical systems through mathematical modeling and computational techniques.<br><br> My current research at UCSD involves using game-theoretic modeling and to create decision-making frameworks, particularly exploring cognitive biases in AI systems and strategic interactions within multilayer networks. I use various tools to contribute to the cutting-edge science such as user studies and surveys, mathematical modeling and optimization, network systems simulation, and game theory.<br><br> On my free time I build interactive frameworks and decision-support tools aimed at enhancing human decision-making processes and providing clear insights into complex, interconnected data scenarios. Before coming to UCSD, I earned dual Bachelor's degrees in Industrial Engineering and Physics from Sharif University of Technology in Tehran, Iran. Beyond academics, I'm passionate about algorithmic trading and financial markets, photography, and rock climbing!<br><br> Thanks for visiting my webpage!"
        
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Projects
            #   url: data/
            # - name: Books
            #   url: books/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:raman@ucsd.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=88OyKqwAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/RamanEbrahimi
        - name: LinkedIn
          url: https://www.linkedin.com/in/ramanebrahimi/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Raman Ebrahimi"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2